# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cloud.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63loud.proto\"^\n\x1eLeaderToViewerHeartBeatRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x17\n\x0fsystemLastIndex\x18\x02 \x01(\x05\x12\x15\n\rLeaderAddress\x18\x03 \x01(\t\"S\n\x1fLeaderToViewerHeartBeatResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x14\n\x07message\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message*\"\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x32\x65\n\x05\x43loud\x12\\\n\x17GetOrUpdateSystemLeader\x12\x1f.LeaderToViewerHeartBeatRequest\x1a .LeaderToViewerHeartBeatResponseB\x0c\xaa\x02\tGrpcCloudb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\tGrpcCloud'
  _globals['_STATUS']._serialized_start=196
  _globals['_STATUS']._serialized_end=230
  _globals['_LEADERTOVIEWERHEARTBEATREQUEST']._serialized_start=15
  _globals['_LEADERTOVIEWERHEARTBEATREQUEST']._serialized_end=109
  _globals['_LEADERTOVIEWERHEARTBEATRESPONSE']._serialized_start=111
  _globals['_LEADERTOVIEWERHEARTBEATRESPONSE']._serialized_end=194
  _globals['_CLOUD']._serialized_start=232
  _globals['_CLOUD']._serialized_end=333
# @@protoc_insertion_point(module_scope)
