# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import node_pb2 as node__pb2


class NodeServicesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadFile = channel.stream_unary(
                '/FileService.NodeServices/UploadFile',
                request_serializer=node__pb2.UploadFileRequest.SerializeToString,
                response_deserializer=node__pb2.UploadFileResponse.FromString,
                )
        self.UpdateFile = channel.stream_unary(
                '/FileService.NodeServices/UpdateFile',
                request_serializer=node__pb2.UpdateFileRequest.SerializeToString,
                response_deserializer=node__pb2.UpdateFileResponse.FromString,
                )
        self.DownloadFile = channel.unary_stream(
                '/FileService.NodeServices/DownloadFile',
                request_serializer=node__pb2.DownloadFileRequest.SerializeToString,
                response_deserializer=node__pb2.DownloadFileResponse.FromString,
                )
        self.DeleteFile = channel.unary_unary(
                '/FileService.NodeServices/DeleteFile',
                request_serializer=node__pb2.DeleteFileRequest.SerializeToString,
                response_deserializer=node__pb2.DeleteFileResponse.FromString,
                )


class NodeServicesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadFile(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFile(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServicesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=node__pb2.UploadFileRequest.FromString,
                    response_serializer=node__pb2.UploadFileResponse.SerializeToString,
            ),
            'UpdateFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UpdateFile,
                    request_deserializer=node__pb2.UpdateFileRequest.FromString,
                    response_serializer=node__pb2.UpdateFileResponse.SerializeToString,
            ),
            'DownloadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=node__pb2.DownloadFileRequest.FromString,
                    response_serializer=node__pb2.DownloadFileResponse.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=node__pb2.DeleteFileRequest.FromString,
                    response_serializer=node__pb2.DeleteFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FileService.NodeServices', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NodeServices(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/FileService.NodeServices/UploadFile',
            node__pb2.UploadFileRequest.SerializeToString,
            node__pb2.UploadFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/FileService.NodeServices/UpdateFile',
            node__pb2.UpdateFileRequest.SerializeToString,
            node__pb2.UpdateFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/FileService.NodeServices/DownloadFile',
            node__pb2.DownloadFileRequest.SerializeToString,
            node__pb2.DownloadFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FileService.NodeServices/DeleteFile',
            node__pb2.DeleteFileRequest.SerializeToString,
            node__pb2.DeleteFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
