# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nnode.proto\"Y\n\x11UploadFileRequest\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x14\n\x0c\x66ile_content\x18\x03 \x01(\x0c\x12\x0f\n\x07user_id\x18\x04 \x01(\x05\"5\n\x12UploadFileResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"J\n\x11UpdateFileRequest\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12\x13\n\x0bnew_content\x18\x03 \x01(\x0c\x12\x0f\n\x07user_id\x18\x04 \x01(\x05\"5\n\x12UpdateFileResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"7\n\x13\x44ownloadFileRequest\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\x05\"^\n\x14\x44ownloadFileResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x14\n\x0c\x66ile_content\x18\x02 \x01(\x0c\x12\x14\n\x07message\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message\"5\n\x11\x44\x65leteFileRequest\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\x05\"5\n\x12\x44\x65leteFileResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xf6\x01\n\x0cNodeServices\x12\x37\n\nUploadFile\x12\x12.UploadFileRequest\x1a\x13.UploadFileResponse(\x01\x12\x37\n\nUpdateFile\x12\x12.UpdateFileRequest\x1a\x13.UpdateFileResponse(\x01\x12=\n\x0c\x44ownloadFile\x12\x14.DownloadFileRequest\x1a\x15.DownloadFileResponse0\x01\x12\x35\n\nDeleteFile\x12\x12.DeleteFileRequest\x1a\x13.DeleteFileResponseB\x11\xaa\x02\x0eGrpcNodeServerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'node_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\016GrpcNodeServer'
  _globals['_UPLOADFILEREQUEST']._serialized_start=14
  _globals['_UPLOADFILEREQUEST']._serialized_end=103
  _globals['_UPLOADFILERESPONSE']._serialized_start=105
  _globals['_UPLOADFILERESPONSE']._serialized_end=158
  _globals['_UPDATEFILEREQUEST']._serialized_start=160
  _globals['_UPDATEFILEREQUEST']._serialized_end=234
  _globals['_UPDATEFILERESPONSE']._serialized_start=236
  _globals['_UPDATEFILERESPONSE']._serialized_end=289
  _globals['_DOWNLOADFILEREQUEST']._serialized_start=291
  _globals['_DOWNLOADFILEREQUEST']._serialized_end=346
  _globals['_DOWNLOADFILERESPONSE']._serialized_start=348
  _globals['_DOWNLOADFILERESPONSE']._serialized_end=442
  _globals['_DELETEFILEREQUEST']._serialized_start=444
  _globals['_DELETEFILEREQUEST']._serialized_end=497
  _globals['_DELETEFILERESPONSE']._serialized_start=499
  _globals['_DELETEFILERESPONSE']._serialized_end=552
  _globals['_NODESERVICES']._serialized_start=555
  _globals['_NODESERVICES']._serialized_end=801
# @@protoc_insertion_point(module_scope)
