version: "3"
networks:
    system-net:
        ipam:
            driver: default
            config:
                - subnet: "172.18.0.0/16"
services: 
    node_server:
        image: node_server:0.1
        container_name: node_server-container
        ports:
        - "50052:50052"
        expose:
        - "50052"
        environment:
        - NODES_ADDRESSES=172.18.0.4:50052,172.18.0.5:50052,172.18.0.6:50052
        - NODE_SERVER_ID=1
        - CLOUD_SERVER_ADDRESS=172.18.0.3:50053
        - NODE_SERVER_ADDRESS=172.18.0.4:50052
        - REGION_ID=USA
        depends_on:
            - "db_server"
        restart: always
        networks:
            system-net:
                ipv4_address: "172.18.0.4"
          
    node_server2:
        image: node_server:0.1
        container_name: node_server2-container
        restart: always
        expose:
        - "50052"
        environment:
        - NODES_ADDRESSES=172.18.0.4:50052,172.18.0.5:50052,172.18.0.6:50052
        - NODE_SERVER_ID=2
        - CLOUD_SERVER_ADDRESS=172.18.0.3:50053
        - NODE_SERVER_ADDRESS=172.18.0.5:50052
        - REGION_ID=UK
        networks:
            system-net:
                ipv4_address: "172.18.0.5"  
        
    node_server3:
        image: node_server:0.1
        container_name: node_server3-container
        restart: always
        expose:
        - "50052"
        environment:
        - NODES_ADDRESSES=172.18.0.4:50052,172.18.0.5:50052,172.18.0.6:50052
        - NODE_SERVER_ID=3
        - CLOUD_SERVER_ADDRESS=172.18.0.3:50053
        - NODE_SERVER_ADDRESS=172.18.0.6:50052
        - REGION_ID=Asia
        networks:
            system-net:
                ipv4_address: "172.18.0.6"