# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_saving_microservice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x66ile_saving_microservice.proto\"G\n\x11UploadFileRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x11\n\tfile_data\x18\x03 \x01(\x0c\"\x14\n\x12UploadFileResponse\"(\n\x13\x44ownloadFileRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\")\n\x14\x44ownloadFileResponse\x12\x11\n\tfile_data\x18\x01 \x01(\x0c\"&\n\x11\x44\x65leteFileRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\"\x14\n\x12\x44\x65leteFileResponse2\xbe\x01\n\x0f\x46ileCloudAccess\x12\x37\n\nUploadFile\x12\x12.UploadFileRequest\x1a\x13.UploadFileResponse(\x01\x12;\n\x0c\x44ownloadFile\x12\x12.UploadFileRequest\x1a\x15.DownloadFileResponse0\x01\x12\x35\n\nDeleteFile\x12\x12.DeleteFileRequest\x1a\x13.DeleteFileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_saving_microservice_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UPLOADFILEREQUEST']._serialized_start=34
  _globals['_UPLOADFILEREQUEST']._serialized_end=105
  _globals['_UPLOADFILERESPONSE']._serialized_start=107
  _globals['_UPLOADFILERESPONSE']._serialized_end=127
  _globals['_DOWNLOADFILEREQUEST']._serialized_start=129
  _globals['_DOWNLOADFILEREQUEST']._serialized_end=169
  _globals['_DOWNLOADFILERESPONSE']._serialized_start=171
  _globals['_DOWNLOADFILERESPONSE']._serialized_end=212
  _globals['_DELETEFILEREQUEST']._serialized_start=214
  _globals['_DELETEFILEREQUEST']._serialized_end=252
  _globals['_DELETEFILERESPONSE']._serialized_start=254
  _globals['_DELETEFILERESPONSE']._serialized_end=274
  _globals['_FILECLOUDACCESS']._serialized_start=277
  _globals['_FILECLOUDACCESS']._serialized_end=467
# @@protoc_insertion_point(module_scope)
