version: "3"
networks:
    system-net:
        ipam:
            driver: default
            config:
                - subnet: "172.18.0.0/16"
services:
    db_server:
        image: postgres:latest
        container_name: db_server-container
        environment:
        - POSTGRES_USER=DBserver
        - POSTGRES_PASSWORD=123AvIt456
        - POSTGRES_DB=mydatabase
        ports:
        - "5432:5432"
        expose:
        - "5432"
        restart: always
        networks:
            system-net:
                ipv4_address: "172.18.0.2"
        command: ["postgres", "-c", "listen_addresses=*"]
        
    cloud_server:
        image: cloud_server:0.1
        container_name: cloud_server-container
        ports:
        - "50053:50053"
        expose:
        - "50053"
        environment:
        - NODES_IPS="172.18.0.4:172.18.0.5:172.18.0.6"
        restart: always
        depends_on:
            - "db_server"
            - "node_server"
            - "node_server2"
            - "node_server3"
        networks:
            system-net:
                ipv4_address: "172.18.0.3"
     
    node_server:
        image: node_server:0.1
        container_name: node_server-container
        ports:
        - "50052:50052"
        expose:
        - "50052"
        environment:
        - NODE_SERVER_IP="172.18.0.4"
        - NODES_IPS="172.18.0.4:172.18.0.5:172.18.0.6"
        depends_on:
            - "db_server"
        restart: always
        networks:
            system-net:
                ipv4_address: "172.18.0.4"
          
    node_server2:
        image: node_server:0.1
        container_name: node_server2-container
        restart: always
        expose:
        - "50052"
        environment:
        - NODE_SERVER_IP="172.18.0.5"
        - NODES_IPS="172.18.0.4:172.18.0.5:172.18.0.6"
        networks:
            system-net:
                ipv4_address: "172.18.0.5"    
        
    node_server3:
        image: node_server:0.1
        container_name: node_server3-container
        restart: always
        expose:
        - "50052"
        environment:
        - NODE_SERVER_IP="172.18.0.6"
        - NODES_IPS="172.18.0.4:172.18.0.5:172.18.0.6"
        networks:
            system-net:
                ipv4_address: "172.18.0.6"    