# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cloud.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63loud.proto\"2\n\x0cloginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\";\n\rloginResponse\x12\x17\n\x06status\x18\x01 \x01(\x0e\x32\x07.Status\x12\x11\n\tsessionId\x18\x02 \x01(\t\"W\n\rsignupRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x13\n\x0bphoneNumber\x18\x04 \x01(\t\":\n\x0esignupResponse\x12\x17\n\x06status\x18\x01 \x01(\x0e\x32\x07.Status\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\rlogoutRequest\x12\x11\n\tsessionId\x18\x01 \x01(\t\"\x10\n\x0elogoutResponse*\"\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x32\x85\x01\n\x05\x43loud\x12&\n\x05login\x12\r.loginRequest\x1a\x0e.loginResponse\x12)\n\x06signup\x12\x0e.signupRequest\x1a\x0f.signupResponse\x12)\n\x06logout\x12\x0e.logoutRequest\x1a\x0f.logoutResponseB\x0c\xaa\x02\tGrpcCloudb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\tGrpcCloud'
  _globals['_STATUS']._serialized_start=331
  _globals['_STATUS']._serialized_end=365
  _globals['_LOGINREQUEST']._serialized_start=15
  _globals['_LOGINREQUEST']._serialized_end=65
  _globals['_LOGINRESPONSE']._serialized_start=67
  _globals['_LOGINRESPONSE']._serialized_end=126
  _globals['_SIGNUPREQUEST']._serialized_start=128
  _globals['_SIGNUPREQUEST']._serialized_end=215
  _globals['_SIGNUPRESPONSE']._serialized_start=217
  _globals['_SIGNUPRESPONSE']._serialized_end=275
  _globals['_LOGOUTREQUEST']._serialized_start=277
  _globals['_LOGOUTREQUEST']._serialized_end=311
  _globals['_LOGOUTRESPONSE']._serialized_start=313
  _globals['_LOGOUTRESPONSE']._serialized_end=329
  _globals['_CLOUD']._serialized_start=368
  _globals['_CLOUD']._serialized_end=501
# @@protoc_insertion_point(module_scope)
